### ISSUE TITLE
No Attribute Error

### ISSUE THREAD

**Issue by rakreddy5201** [Snowflake-Labs/sfguide-getting-started-with-data-quality-manager#7]
AttributeError: module 'streamlit' has no attribute 'column_config'

File "/home/udf/27317109545/src/metrics_alert_monitoring.py", line 160, in print_page
    "VALUE_HISTORY": st.column_config.AreaChartColumn("Checks (last 14 days)", y_min=0),

**Comment by sfc-gh-hbrown** [comment]
Should be fixed with latest update!
